-- aclicktogo.users updates
update aclicktogo.users set email = 'MegaASM5@hdvnpharma.com', email_info = 'MegaASM5@hdvnpharma.com' where id = 2532239;
update aclicktogo.users set email = 'MegaASM4@hdvnpharma.com', email_info = 'MegaASM4@hdvnpharma.com' where id = 2532331;
update aclicktogo.users set email = 'MegaASM2@hdvnpharma.com', email_info = 'MegaASM2@hdvnpharma.com' where id = 2532385;
update aclicktogo.users set email = 'MegaASM10@hdvnpharma.com', email_info = 'MegaASM10@hdvnpharma.com' where id = 2532412;
update aclicktogo.users set email = 'MegaASM3@hdvnpharma.com', email_info = 'MegaASM3@hdvnpharma.com' where id = 2532428;
update aclicktogo.users set email = 'MegaASM9@hdvnpharma.com', email_info = 'MegaASM9@hdvnpharma.com' where id = 2532425;
update aclicktogo.users set email = 'MegaRSM1@hdvnpharma.com', email_info = 'MegaRSM1@hdvnpharma.com' where id = 2532448;
update aclicktogo.users set email = 'MegaKAM3@hdvnpharma.com', email_info = 'MegaKAM3@hdvnpharma.com' where id = 2679566;
update aclicktogo.users set email = 'MegaNSM@hdvnpharma.com', email_info = 'MegaNSM@hdvnpharma.com' where id = 2690986;
update aclicktogo.users set email = 'MegaKAM2@hdvnpharma.com', email_info = 'MegaKAM2@hdvnpharma.com' where id = 2737889;
update aclicktogo.users set email = 'MegaKAE2@hdvnpharma.com', email_info = 'MegaKAE2@hdvnpharma.com' where id = 2738993;
update aclicktogo.users set email = 'MegaKAE8@hdvnpharma.com', email_info = 'MegaKAE8@hdvnpharma.com' where id = 2738997;
update aclicktogo.users set email = 'MegaKAE13@hdvnpharma.com', email_info = 'MegaKAE13@hdvnpharma.com' where id = 2739000;
update aclicktogo.users set email = 'MegaKAE14@hdvnpharma.com', email_info = 'MegaKAE14@hdvnpharma.com' where id = 2739003;
update aclicktogo.users set email = 'MegaKAE15@hdvnpharma.com', email_info = 'MegaKAE15@hdvnpharma.com' where id = 2739006;
update aclicktogo.users set email = 'MegaASM6@hdvnpharma.com', email_info = 'MegaASM6@hdvnpharma.com' where id = 2739007;
update aclicktogo.users set email = 'MegaKAE6@hdvnpharma.com', email_info = 'MegaKAE6@hdvnpharma.com' where id = 2756837;
update aclicktogo.users set email = 'MegaKAE4@hdvnpharma.com', email_info = 'MegaKAE4@hdvnpharma.com' where id = 2783057;
update aclicktogo.users set email = 'MegaKAE5@hdvnpharma.com', email_info = 'MegaKAE5@hdvnpharma.com' where id = 2783058;
update aclicktogo.users set email = 'MegaKAE9@hdvnpharma.com', email_info = 'MegaKAE9@hdvnpharma.com' where id = 2783061;

-- tripi_one.user updates
update tripi_one.user set email = 'MegaASM5@hdvnpharma.com' where id = 7259;
update tripi_one.user set email = 'MegaASM4@hdvnpharma.com' where id = 7353;
update tripi_one.user set email = 'MegaASM2@hdvnpharma.com' where id = 7411;
update tripi_one.user set email = 'MegaASM10@hdvnpharma.com' where id = 7438;
update tripi_one.user set email = 'MegaASM3@hdvnpharma.com' where id = 7451;
update tripi_one.user set email = 'MegaASM9@hdvnpharma.com' where id = 7453;
update tripi_one.user set email = 'MegaRSM1@hdvnpharma.com' where id = 7474;
update tripi_one.user set email = 'MegaKAM3@hdvnpharma.com' where id = 10136;
update tripi_one.user set email = 'MegaNSM@hdvnpharma.com' where id = 10166;
update tripi_one.user set email = 'MegaKAM2@hdvnpharma.com' where id = 10481;
update tripi_one.user set email = 'MegaKAE2@hdvnpharma.com' where id = 10484;
update tripi_one.user set email = 'MegaKAE8@hdvnpharma.com' where id = 10485;
update tripi_one.user set email = 'MegaKAE13@hdvnpharma.com' where id = 10486;
update tripi_one.user set email = 'MegaKAE14@hdvnpharma.com' where id = 10487;
update tripi_one.user set email = 'MegaKAE15@hdvnpharma.com' where id = 10488;
update tripi_one.user set email = 'MegaASM6@hdvnpharma.com' where id = 10489;
update tripi_one.user set email = 'MegaKAE6@hdvnpharma.com' where id = 10628;
update tripi_one.user set email = 'MegaKAE4@hdvnpharma.com' where id = 10717;
update tripi_one.user set email = 'MegaKAE5@hdvnpharma.com' where id = 10718;
update tripi_one.user set email = 'MegaKAE9@hdvnpharma.com' where id = 10719;
