CREATE TABLE `job_title` ( 
  `id` BIGINT AUTO_INCREMENT NOT NULL,
  `company_id` BIGINT NULL,
  `name` VARCHAR(500) NULL,
  `status` TINYINT NOT NULL DEFAULT 0 ,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP ,
   PRIMARY KEY (`id`),
  CONSTRAINT `job_title_fk1` FOREIGN KEY (`company_id`) REFERENCES `company` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB;
CREATE INDEX `job_title_fk1` 
ON `job_title` (
  `company_id` ASC
);
