
WITH input_emails AS (
    SELECT 'mainc@vnpay.vn' AS email
    UNION ALL SELECT 'thuttn@vnpay.vn' AS email
    UNION ALL SELECT 'trangnth5@vnpay.vn' AS email
    UNION ALL SELECT 'linhtm1@vnpay.vn' AS email
    UNION ALL SELECT 'tuannd4@vnpay.vn' AS email
    UNION ALL SELECT 'anhdg@vnpay.vn' AS email
    UNION ALL SELECT 'huynm@vnpay.vn' AS email
    UNION ALL SELECT 'dongnv2@vnpay.vn' AS email
    UNION ALL SELECT 'linhnd@vnpay.vn' AS email
    UNION ALL SELECT 'longnd5@vnpay.vn' AS email
    UNION ALL SELECT 'lynth@vnpay.vn' AS email
    UNION ALL SELECT 'thaoht5@vnpay.vn' AS email
    UNION ALL SELECT 'dungnt13@vnpay.vn' AS email
    UNION ALL SELECT 'hoannq@vnpay.vn' AS email
    UNION ALL SELECT 'thanhvtn@vnpay.vn' AS email
    UNION ALL SELECT 'quynhpt2@vnpay.vn' AS email
    UNION ALL SELECT 'thuypt3@vnpay.vn' AS email
    UNION ALL SELECT 'hangdm@vnpay.vn' AS email
    UNION ALL SELECT 'tridm1@vnpay.vn' AS email
    UNION ALL SELECT 'tranglq1@vnpay.vn' AS email
    UNION ALL SELECT 'tunh1@vnpay.vn' AS email
    UNION ALL SELECT 'minhtt@vnpay.vn' AS email
    UNION ALL SELECT 'nguyettt@vnpay.vn' AS email
    UNION ALL SELECT 'vintt@vnpay.vn' AS email
    UNION ALL SELECT 'hongnt1@vnpay.vn' AS email
    UNION ALL SELECT 'hiennt@vnpay.vn' AS email
    UNION ALL SELECT 'hangtt@vnpay.vn' AS email
    UNION ALL SELECT 'ngocvtb1@vnpay.vn' AS email
    UNION ALL SELECT 'hoanth@vnpay.vn' AS email
    UNION ALL SELECT 'nguyetnt@vnpay.vn' AS email
    UNION ALL SELECT 'ducnc@vnpay.vn' AS email
    UNION ALL SELECT 'tranglk@vnpay.vn' AS email
    UNION ALL SELECT 'ngatnt@vnpay.vn' AS email
    UNION ALL SELECT 'tuyentt@vnpay.vn' AS email
    UNION ALL SELECT 'anhdtl@vnpay.vn' AS email
    UNION ALL SELECT 'haltt1@vnpay.vn' AS email
    UNION ALL SELECT 'theta@vnpay.vn' AS email
    UNION ALL SELECT 'hamt@vnpay.vn' AS email
    UNION ALL SELECT 'locnh@vnpay.vn' AS email
    UNION ALL SELECT 'hoant1@vnpay.vn' AS email
    UNION ALL SELECT 'haivt@vnpay.vn' AS email
    UNION ALL SELECT 'hadt5@vnpay.vn' AS email
    UNION ALL SELECT 'tramvtb@vnpay.vn' AS email
    UNION ALL SELECT 'phuongnt4@vnpay.vn' AS email
    UNION ALL SELECT 'anhnk3@vnpay.vn' AS email
    UNION ALL SELECT 'yenttk@vnpay.vn' AS email
    UNION ALL SELECT 'danltt@vnpay.vn' AS email
    UNION ALL SELECT 'huept@vnpay.vn' AS email
    UNION ALL SELECT 'phuongttm1@vnpay.vn' AS email
    UNION ALL SELECT 'lyltl@vnpay.vn' AS email
    UNION ALL SELECT 'thaopp2@vnpay.vn' AS email
    UNION ALL SELECT 'thaont1@vnpay.vn' AS email
    UNION ALL SELECT 'maihtn@vnpay.vn' AS email
    UNION ALL SELECT 'lamlq1@vnpay.vn' AS email
    UNION ALL SELECT 'phuongnt6@vnpay.vn' AS email
    UNION ALL SELECT 'linhtt2@vnpay.vn' AS email
    UNION ALL SELECT 'giangtt@vnpay.vn' AS email
    UNION ALL SELECT 'chittl@vnpay.vn' AS email
    UNION ALL SELECT 'tranglth@vnpay.vn' AS email
    UNION ALL SELECT 'lylth@vnpay.vn' AS email
    UNION ALL SELECT 'vietnn@vnpay.vn' AS email
    UNION ALL SELECT 'manhdv@vnpay.vn' AS email
    UNION ALL SELECT 'luongnt1@vnpay.vn' AS email
    UNION ALL SELECT 'linhdtt@vnpay.vn' AS email
    UNION ALL SELECT 'hoangcv@vnpay.vn' AS email
    UNION ALL SELECT 'thanhctl1@vnpay.vn' AS email
    UNION ALL SELECT 'maivtt@vnpay.vn' AS email
    UNION ALL SELECT 'huentm@vnpay.vn' AS email
    UNION ALL SELECT 'anhltl@vnpay.vn' AS email
    UNION ALL SELECT 'huongnm@vnpay.vn' AS email
    UNION ALL SELECT 'hauvth@vnpay.vn' AS email
    UNION ALL SELECT 'lanpt@vnpay.vn' AS email
    UNION ALL SELECT 'manhpd@vnpay.vn' AS email
    UNION ALL SELECT 'dungdt3@vnpay.vn' AS email
    UNION ALL SELECT 'huent@vnpay.vn' AS email
    UNION ALL SELECT 'congdt@vnpay.vn' AS email
    UNION ALL SELECT 'huedt1@vnpay.vn' AS email
    UNION ALL SELECT 'thanhtt1@vnpay.vn' AS email
    UNION ALL SELECT 'ducnth@vnpay.vn' AS email
    UNION ALL SELECT 'sonnt4@vnpay.vn' AS email
    UNION ALL SELECT 'minhph@vnpay.vn' AS email
    UNION ALL SELECT 'thaopt@vnpay.vn' AS email
    UNION ALL SELECT 'anhbtv1@vnpay.vn' AS email
    UNION ALL SELECT 'huedt3@vnpay.vn' AS email
    UNION ALL SELECT 'tuct@vnpay.vn' AS email
    UNION ALL SELECT 'nhihhy1@vnpay.vn' AS email
    UNION ALL SELECT 'hongnt3@vnpay.vn' AS email
    UNION ALL SELECT 'loanttk@vnpay.vn' AS email
    UNION ALL SELECT 'thaontp5@vnpay.vn' AS email
    UNION ALL SELECT 'huyendtn@vnpay.vn' AS email
    UNION ALL SELECT 'quynhttn1@vnpay.vn' AS email
    UNION ALL SELECT 'maidtt2@vnpay.vn' AS email
    UNION ALL SELECT 'tuanha8@vnpay.vn' AS email
    UNION ALL SELECT 'ngannk@vnpay.vn' AS email
    UNION ALL SELECT 'thaodtm@vnpay.vn' AS email
    UNION ALL SELECT 'phivq@vnpay.vn' AS email
    UNION ALL SELECT 'haimth@vnpay.vn' AS email
    UNION ALL SELECT 'huyenltt2@vnpay.vn' AS email
    UNION ALL SELECT 'hieuhc@vnpay.vn' AS email
    UNION ALL SELECT 'hoant6@vnpay.vn' AS email
    UNION ALL SELECT 'duyenmt@vnpay.vn' AS email
    UNION ALL SELECT 'loanpt@vnpay.vn' AS email
    UNION ALL SELECT 'nhungnt4@vnpay.vn' AS email
    UNION ALL SELECT 'yenvt@vnpay.vn' AS email
    UNION ALL SELECT 'thamct@vnpay.vn' AS email
    UNION ALL SELECT 'hangtt4@vnpay.vn' AS email
    UNION ALL SELECT 'suongtt@vnpay.vn' AS email
    UNION ALL SELECT 'anhhtp@vnpay.vn' AS email
    UNION ALL SELECT 'minhph2@vnpay.vn' AS email
    UNION ALL SELECT 'tungbt1@vnpay.vn' AS email
    UNION ALL SELECT 'phuongqn@vnpay.vn' AS email
    UNION ALL SELECT 'quynhvt@vnpay.vn' AS email
    UNION ALL SELECT 'chibtl@vnpay.vn' AS email
    UNION ALL SELECT 'thanhnt13@vnpay.vn' AS email
    UNION ALL SELECT 'lyptt@vnpay.vn' AS email
    UNION ALL SELECT 'liennt@vnpay.vn' AS email
    UNION ALL SELECT 'hangnt15@vnpay.vn' AS email
    UNION ALL SELECT 'anhntk1@vnpay.vn' AS email
    UNION ALL SELECT 'tinhnt@vnpay.vn' AS email
    UNION ALL SELECT 'nhuntq1@vnpay.vn' AS email
    UNION ALL SELECT 'hoantt4@vnpay.vn' AS email
    UNION ALL SELECT 'nhungpth6@vnpay.vn' AS email
    UNION ALL SELECT 'hoanntt@vnpay.vn' AS email
    UNION ALL SELECT 'hangpt2@vnpay.vn' AS email
    UNION ALL SELECT 'binhnp@vnpay.vn' AS email
    UNION ALL SELECT 'dattn@vnpay.vn' AS email
    UNION ALL SELECT 'tamnt6@vnpay.vn' AS email
    UNION ALL SELECT 'minhnt2@vnpay.vn' AS email
    UNION ALL SELECT 'linhnd2@vnpay.vn' AS email
    UNION ALL SELECT 'hangbt1@vnpay.vn' AS email
    UNION ALL SELECT 'huemt@vnpay.vn' AS email
    UNION ALL SELECT 'huent5@vnpay.vn' AS email
    UNION ALL SELECT 'tuyetnt1@vnpay.vn' AS email
    UNION ALL SELECT 'hoatt2@vnpay.vn' AS email
    UNION ALL SELECT 'lynh@vnpay.vn' AS email
    UNION ALL SELECT 'anhhtp1@vnpay.vn' AS email
    UNION ALL SELECT 'nhungdth1@vnpay.vn' AS email
    UNION ALL SELECT 'longlv@vnpay.vn' AS email
    UNION ALL SELECT 'lampt@vnpay.vn' AS email
    UNION ALL SELECT 'thodp@vnpay.vn' AS email
    UNION ALL SELECT 'leqt@vnpay.vn' AS email
    UNION ALL SELECT 'hoactt@vnpay.vn' AS email
    UNION ALL SELECT 'hiephm@vnpay.vn' AS email
    UNION ALL SELECT 'anhctv@vnpay.vn' AS email
    UNION ALL SELECT 'tamht@vnpay.vn' AS email
    UNION ALL SELECT 'tamnt3@vnpay.vn' AS email
    UNION ALL SELECT 'huydh@vnpay.vn' AS email
    UNION ALL SELECT 'phucnt@vnpay.vn' AS email
    UNION ALL SELECT 'huongnt6@vnpay.vn' AS email
    UNION ALL SELECT 'trungnd2@vnpay.vn' AS email
    UNION ALL SELECT 'phuongll@vnpay.vn' AS email
    UNION ALL SELECT 'thudtm@vnpay.vn' AS email
    UNION ALL SELECT 'giangpth@vnpay.vn' AS email
    UNION ALL SELECT 'lienht@vnpay.vn' AS email
    UNION ALL SELECT 'anhbtk@vnpay.vn' AS email
    UNION ALL SELECT 'trungpd@vnpay.vn' AS email
    UNION ALL SELECT 'tuanph@vnpay.vn' AS email
    UNION ALL SELECT 'truongpv@vnpay.vn' AS email
    UNION ALL SELECT 'khaidq1@vnpay.vn' AS email
    UNION ALL SELECT 'minhln@vnpay.vn' AS email
    UNION ALL SELECT 'thuyhtt1@vnpay.vn' AS email
    UNION ALL SELECT 'hungdv1@vnpay.vn' AS email
    UNION ALL SELECT 'vietlt@vnpay.vn' AS email
    UNION ALL SELECT 'hoangnh1@vnpay.vn' AS email
    UNION ALL SELECT 'hieppt@vnpay.vn' AS email
    UNION ALL SELECT 'trangdtk@vnpay.vn' AS email
    UNION ALL SELECT 'khanhhm@vnpay.vn' AS email
    UNION ALL SELECT 'thoaltk@vnpay.vn' AS email
    UNION ALL SELECT 'huyenbtt1@vnpay.vn' AS email
    UNION ALL SELECT 'honglt@vnpay.vn' AS email
    UNION ALL SELECT 'huongpt3@vnpay.vn' AS email
    UNION ALL SELECT 'thuongnth1@vnpay.vn' AS email
    UNION ALL SELECT 'dungdtl@vnpay.vn' AS email
    UNION ALL SELECT 'trangnh2@vnpay.vn' AS email
    UNION ALL SELECT 'baodlt@vnpay.vn' AS email
    UNION ALL SELECT 'thaiph@vnpay.vn' AS email
    UNION ALL SELECT 'annt4@vnpay.vn' AS email
    UNION ALL SELECT 'nhungdh@vnpay.vn' AS email
    UNION ALL SELECT 'huongnt9@vnpay.vn' AS email
    UNION ALL SELECT 'linhpp1@vnpay.vn' AS email
    UNION ALL SELECT 'tuanvn1@vnpay.vn' AS email
    UNION ALL SELECT 'vinhnp@vnpay.vn' AS email
    UNION ALL SELECT 'huyenntt4@vnpay.vn' AS email
    UNION ALL SELECT 'linhth1@vnpay.vn' AS email
    UNION ALL SELECT 'handtn1@vnpay.vn' AS email
    UNION ALL SELECT 'huyennbk@vnpay.vn' AS email
    UNION ALL SELECT 'lienttm@vnpay.vn' AS email
    UNION ALL SELECT 'maintn@vnpay.vn' AS email
    UNION ALL SELECT 'hangnt12@vnpay.vn' AS email
    UNION ALL SELECT 'nhungpth4@vnpay.vn' AS email
    UNION ALL SELECT 'ngocnln@vnpay.vn' AS email
    UNION ALL SELECT 'hienntt5@vnpay.vn' AS email
    UNION ALL SELECT 'thudm2@vnpay.vn' AS email
    UNION ALL SELECT 'nhapt@vnpay.vn' AS email
    UNION ALL SELECT 'linhhd1@vnpay.vn' AS email
    UNION ALL SELECT 'huyhn1@vnpay.vn' AS email
    UNION ALL SELECT 'nhamnt@vnpay.vn' AS email
    UNION ALL SELECT 'baopg1@vnpay.vn' AS email
    UNION ALL SELECT 'quangdd@vnpay.vn' AS email
    UNION ALL SELECT 'phuongltl@vnpay.vn' AS email
    UNION ALL SELECT 'thaocy@vnpay.vn' AS email
    UNION ALL SELECT 'trangnth6@vnpay.vn' AS email
    UNION ALL SELECT 'trantt@vnpay.vn' AS email
    UNION ALL SELECT 'anhttk1@vnpay.vn' AS email
    UNION ALL SELECT 'dutt@vnpay.vn' AS email
    UNION ALL SELECT 'nhungnth8@vnpay.vn' AS email
    UNION ALL SELECT 'tuanhm5@vnpay.vn' AS email
    UNION ALL SELECT 'trangnth8@vnpay.vn' AS email
    UNION ALL SELECT 'chinl1@vnpay.vn' AS email
    UNION ALL SELECT 'khanhpt@vnpay.vn' AS email
    UNION ALL SELECT 'giangnth5@vnpay.vn' AS email
    UNION ALL SELECT 'thanhlv@vnpay.vn' AS email
    UNION ALL SELECT 'tranglh2@vnpay.vn' AS email
    UNION ALL SELECT 'ngocdm@vnpay.vn' AS email
    UNION ALL SELECT 'quypv1@vnpay.vn' AS email
    UNION ALL SELECT 'trangntk1@vnpay.vn' AS email
    UNION ALL SELECT 'hoangth1@vnpay.vn' AS email
    UNION ALL SELECT 'anhntv4@vnpay.vn' AS email
    UNION ALL SELECT 'ductl@vnpay.vn' AS email
    UNION ALL SELECT 'nhannt5@vnpay.vn' AS email
    UNION ALL SELECT 'yentth@vnpay.vn' AS email
    UNION ALL SELECT 'ngandth@vnpay.vn' AS email
    UNION ALL SELECT 'dungtt@vnpay.vn' AS email
    UNION ALL SELECT 'lytt@vnpay.vn' AS email
    UNION ALL SELECT 'trungvt3@vnpay.vn' AS email
    UNION ALL SELECT 'phuongdtm@vnpay.vn' AS email
    UNION ALL SELECT 'lapnv@vnpay.vn' AS email
    UNION ALL SELECT 'hangnt8@vnpay.vn' AS email
    UNION ALL SELECT 'thuytt@vnpay.vn' AS email
    UNION ALL SELECT 'tranth@vnpay.vn' AS email
    UNION ALL SELECT 'tuttc@vnpay.vn' AS email
    UNION ALL SELECT 'mont@vnpay.vn' AS email
    UNION ALL SELECT 'tuoibt@vnpay.vn' AS email
    UNION ALL SELECT 'dinhnt@vnpay.vn' AS email
    UNION ALL SELECT 'minhvn1@vnpay.vn' AS email
    UNION ALL SELECT 'hanhntm2@vnpay.vn' AS email
    UNION ALL SELECT 'huongltm@vnpay.vn' AS email
    UNION ALL SELECT 'chinh@vnpay.vn' AS email
    UNION ALL SELECT 'phuongnm4@vnpay.vn' AS email
    UNION ALL SELECT 'thuyptt3@vnpay.vn' AS email
    UNION ALL SELECT 'hanhptm1@vnpay.vn' AS email
    UNION ALL SELECT 'huyenntk1@vnpay.vn' AS email
    UNION ALL SELECT 'anhptt@vnpay.vn' AS email
    UNION ALL SELECT 'hiendt2@vnpay.vn' AS email
    UNION ALL SELECT 'trinhtk@vnpay.vn' AS email
    UNION ALL SELECT 'linhpp@vnpay.vn' AS email
    UNION ALL SELECT 'thuykt@vnpay.vn' AS email
    UNION ALL SELECT 'hangdtt@vnpay.vn' AS email
    UNION ALL SELECT 'duyennt@vnpay.vn' AS email
    UNION ALL SELECT 'nguyetbta@vnpay.vn' AS email
    UNION ALL SELECT 'nhatvt@vnpay.vn' AS email
    UNION ALL SELECT 'mainh@vnpay.vn' AS email
    UNION ALL SELECT 'tungnn1@vnpay.vn' AS email
    UNION ALL SELECT 'vandt2@vnpay.vn' AS email
    UNION ALL SELECT 'thaoltp1@vnpay.vn' AS email
    UNION ALL SELECT 'chinhnt2@vnpay.vn' AS email
    UNION ALL SELECT 'tannvn@vnpay.vn' AS email
    UNION ALL SELECT 'longtt1@vnpay.vn' AS email
    UNION ALL SELECT 'ngoctv1@vnpay.vn' AS email
    UNION ALL SELECT 'hapt3@vnpay.vn' AS email
    UNION ALL SELECT 'nhungnt3@vnpay.vn' AS email
    UNION ALL SELECT 'anhmtt@vnpay.vn' AS email
    UNION ALL SELECT 'phuongbk@vnpay.vn' AS email
    UNION ALL SELECT 'linhnp1@vnpay.vn' AS email
    UNION ALL SELECT 'trangnt7@vnpay.vn' AS email
    UNION ALL SELECT 'anhtth1@vnpay.vn' AS email
    UNION ALL SELECT 'anhntm1@vnpay.vn' AS email
    UNION ALL SELECT 'huongnm4@vnpay.vn' AS email
    UNION ALL SELECT 'nguyetnt3@vnpay.vn' AS email
    UNION ALL SELECT 'huongntg@vnpay.vn' AS email
    UNION ALL SELECT 'chilq1@vnpay.vn' AS email
    UNION ALL SELECT 'duonght1@vnpay.vn' AS email
    UNION ALL SELECT 'huypq@vnpay.vn' AS email
    UNION ALL SELECT 'hanm@vnpay.vn' AS email
    UNION ALL SELECT 'dungdtk@vnpay.vn' AS email
    UNION ALL SELECT 'hadn@vnpay.vn' AS email
    UNION ALL SELECT 'phuongnn@vnpay.vn' AS email
    UNION ALL SELECT 'cuongnt@vnpay.vn' AS email
    UNION ALL SELECT 'trangnt@vnpay.vn' AS email
    UNION ALL SELECT 'thuydh@vnpay.vn' AS email
    UNION ALL SELECT 'chiph@vnpay.vn' AS email
    UNION ALL SELECT 'hiendtt1@vnpay.vn' AS email
    UNION ALL SELECT 'yentb@vnpay.vn' AS email
    UNION ALL SELECT 'anhnn4@vnpay.vn' AS email
    UNION ALL SELECT 'linhnt17@vnpay.vn' AS email
    UNION ALL SELECT 'anhtc2@vnpay.vn' AS email
    UNION ALL SELECT 'hoank@vnpay.vn' AS email
    UNION ALL SELECT 'minhvq@vnpay.vn' AS email
    UNION ALL SELECT 'maidn1@vnpay.vn' AS email
    UNION ALL SELECT 'hangntm1@vnpay.vn' AS email
    UNION ALL SELECT 'linhhp1@vnpay.vn' AS email
    UNION ALL SELECT 'trangnh7@vnpay.vn' AS email
    UNION ALL SELECT 'hieunt@vnpay.vn' AS email
    UNION ALL SELECT 'anptt@vnpay.vn' AS email
    UNION ALL SELECT 'tiendtt2@vnpay.vn' AS email
    UNION ALL SELECT 'hoangdv@vnpay.vn' AS email
    UNION ALL SELECT 'anptb1@vnpay.vn' AS email
    UNION ALL SELECT 'huyenth@vnpay.vn' AS email
    UNION ALL SELECT 'hapt4@vnpay.vn' AS email
    UNION ALL SELECT 'huydq2@vnpay.vn' AS email
    UNION ALL SELECT 'dungntp@vnpay.vn' AS email
    UNION ALL SELECT 'thienha@vnpay.vn' AS email
    UNION ALL SELECT 'quynhtn@vnpay.vn' AS email
    UNION ALL SELECT 'hieunh@vnpay.vn' AS email
    UNION ALL SELECT 'longnq@vnpay.vn' AS email
    UNION ALL SELECT 'hungv@vnpay.vn' AS email
    UNION ALL SELECT 'tungnt2@vnpay.vn' AS email
    UNION ALL SELECT 'nhungnth3@vnpay.vn' AS email
    UNION ALL SELECT 'haonv@vnpay.vn' AS email
    UNION ALL SELECT 'quanvv@vnpay.vn' AS email
    UNION ALL SELECT 'giapnh@vnpay.vn' AS email
    UNION ALL SELECT 'tungn@vnpay.vn' AS email
    UNION ALL SELECT 'phongpd@vnpay.vn' AS email
    UNION ALL SELECT 'thaotlp@vnpay.vn' AS email
    UNION ALL SELECT 'nganvt1@vnpay.vn' AS email
    UNION ALL SELECT 'ngocln@vnpay.vn' AS email
    UNION ALL SELECT 'ngocntk@vnpay.vn' AS email
    UNION ALL SELECT 'phuongna@vnpay.vn' AS email
    UNION ALL SELECT 'anhnd13@vnpay.vn' AS email
    UNION ALL SELECT 'netnt@vnpay.vn' AS email
    UNION ALL SELECT 'duynl@vnpay.vn' AS email
    UNION ALL SELECT 'uyenntt1@vnpay.vn' AS email
    UNION ALL SELECT 'lynk2@vnpay.vn' AS email
    UNION ALL SELECT 'anhdtm@vnpay.vn' AS email
    UNION ALL SELECT 'dattt2@vnpay.vn' AS email
    UNION ALL SELECT 'hoadt@vnpay.vn' AS email
    UNION ALL SELECT 'huongtl1@vnpay.vn' AS email
    UNION ALL SELECT 'thuongnt3@vnpay.vn' AS email
    UNION ALL SELECT 'minhhn@vnpay.vn' AS email
    UNION ALL SELECT 'anhnq5@vnpay.vn' AS email
    UNION ALL SELECT 'dunglt1@vnpay.vn' AS email
    UNION ALL SELECT 'linhln3@vnpay.vn' AS email
    UNION ALL SELECT 'tuyenhnl@vnpay.vn' AS email
    UNION ALL SELECT 'trangntq1@vnpay.vn' AS email
    UNION ALL SELECT 'trangntk@vnpay.vn' AS email
    UNION ALL SELECT 'maiptn@vnpay.vn' AS email
    UNION ALL SELECT 'dinhdc@vnpay.vn' AS email
    UNION ALL SELECT 'dungnt12@vnpay.vn' AS email
    UNION ALL SELECT 'linhvlk@vnpay.vn' AS email
    UNION ALL SELECT 'duongpm@vnpay.vn' AS email
    UNION ALL SELECT 'dungnn@vnpay.vn' AS email
    UNION ALL SELECT 'minhdh@vnpay.vn' AS email
    UNION ALL SELECT 'tungpt@vnpay.vn' AS email
    UNION ALL SELECT 'nguyennt@vnpay.vn' AS email
    UNION ALL SELECT 'bachnv1@vnpay.vn' AS email
    UNION ALL SELECT 'phongnn@vnpay.vn' AS email
    UNION ALL SELECT 'trangdt@vnpay.vn' AS email
    UNION ALL SELECT 'luanch@vnpay.vn' AS email
    UNION ALL SELECT 'cuongtt@vnpay.vn' AS email
    UNION ALL SELECT 'huonglq@vnpay.vn' AS email
    UNION ALL SELECT 'trungth@vnpay.vn' AS email
    UNION ALL SELECT 'linhnt11@vnpay.vn' AS email
    UNION ALL SELECT 'huulc@vnpay.vn' AS email
    UNION ALL SELECT 'minhtb@vnpay.vn' AS email
    UNION ALL SELECT 'uyenntt3@vnpay.vn' AS email
    UNION ALL SELECT 'hanmn@vnpay.vn' AS email
    UNION ALL SELECT 'nguyettta@vnpay.vn' AS email
    UNION ALL SELECT 'datvt@vnpay.vn' AS email
    UNION ALL SELECT 'nguyetnt1@vnpay.vn' AS email
    UNION ALL SELECT 'minhlq@vnpay.vn' AS email
    UNION ALL SELECT 'linhnm3@vnpay.vn' AS email
    UNION ALL SELECT 'haivk@vnpay.vn' AS email
    UNION ALL SELECT 'linhnt10@vnpay.vn' AS email
    UNION ALL SELECT 'minhttk@vnpay.vn' AS email
    UNION ALL SELECT 'trucnvt@vnpay.vn' AS email
    UNION ALL SELECT 'anlnh@vnpay.vn' AS email
    UNION ALL SELECT 'thiennt1@vnpay.vn' AS email
    UNION ALL SELECT 'lyhh@vnpay.vn' AS email
    UNION ALL SELECT 'diepvtb@vnpay.vn' AS email
    UNION ALL SELECT 'linhny@vnpay.vn' AS email
    UNION ALL SELECT 'quanlm@vnpay.vn' AS email
    UNION ALL SELECT 'vuonglv@vnpay.vn' AS email
    UNION ALL SELECT 'tunn2@vnpay.vn' AS email
    UNION ALL SELECT 'anhdt10@vnpay.vn' AS email
    UNION ALL SELECT 'hungtd2@vnpay.vn' AS email
    UNION ALL SELECT 'datnt18@vnpay.vn' AS email
    UNION ALL SELECT 'ngochxt@vnpay.vn' AS email
    UNION ALL SELECT 'thaonp8@vnpay.vn' AS email
    UNION ALL SELECT 'loanlt@vnpay.vn' AS email
)
SELECT i.email 
FROM input_emails i
LEFT JOIN user u ON i.email = u.email
WHERE u.email IS NULL;
